theme: jekyll-theme-minimal
title: Jorin Overwiening
description: PhD student in Physics
author: Jorin Overwiening
email: joverwiening@fas.harvard.edu
url: "https://joverwiening.github.io"

# Social links
github_username: joverwiening
linkedin_username: joverwiening
linkedin_url: "https://www.linkedin.com/in/joverwiening/"
google_scholar: "https://scholar.google.com/citations?user=XDpDiuYAAAAJ&hl=en"

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Exclude files
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md